FROM almalinux:9
# CMD ["ping", "google.com"] ===> it can be override in cmd line
# ENTRYPOINT ["ping", "google.com"]  ====> it can't be override
# if you give only argument to CMD and Pingto Entrypoint , like this you can override entrypoint
CMD ["ping"]
ENTRYPOINT ["google.com"]  
 